# Generated by Django 5.2.8 on 2025-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WISHLIST", "Wishlist"),
                            ("APPLIED", "Applied"),
                            ("INTERVIEW", "Interview"),
                            ("OFFER", "Offer"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="WISHLIST",
                        max_length=200,
                    ),
                ),
            ],
        ),
    ]
